-- 장비 데이터 INSERT (자동 생성: 2026-01-15)
-- 총 469개

-- Batch 1
INSERT INTO equipments (id, original_index, name, category, spec, location, sub_location, quantity, unit, serial_number, status, notes, is_material)
VALUES
  ('MS-001-A', '1', '4K Camcoder', 'Studio Camera System', 'PXW-Z280', '메인 스튜디오', '스튜디오', 1, 'EA', '1002527', 'NORMAL', '', false),
  ('MS-001-B', '1', '4K Camcoder', 'Studio Camera System', 'PXW-Z280', '메인 스튜디오', '스튜디오', 1, 'EA', '1002509', 'NORMAL', '', false),
  ('MS-001-C', '1', '4K Camcoder', 'Studio Camera System', 'PXW-Z280', '메인 스튜디오', '스튜디오', 1, 'EA', '1002505', 'NORMAL', '', false),
  ('MS-002-A', '2', 'Camera Tally Lamp', 'Studio Camera System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-002-B', '2', 'Camera Tally Lamp', 'Studio Camera System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-002-C', '2', 'Camera Tally Lamp', 'Studio Camera System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-003-A', '3', 'Battery Pack', 'Studio Camera System', 'BP-U70', '메인 스튜디오', '조정실', 1, 'EA', '1005538', 'NORMAL', '', false),
  ('MS-003-B', '3', 'Battery Pack', 'Studio Camera System', 'BP-U70', '메인 스튜디오', '조정실', 1, 'EA', '1005537', 'NORMAL', '', false),
  ('MS-003-C', '3', 'Battery Pack', 'Studio Camera System', 'BP-U70', '메인 스튜디오', '조정실', 1, 'EA', '1006324', 'NORMAL', '', false),
  ('MS-003-D', '3', 'Battery Pack', 'Studio Camera System', 'BP-U70', '메인 스튜디오', '조정실', 1, 'EA', '1005534', 'NORMAL', '', false),
  ('MS-003-E', '3', 'Battery Pack', 'Studio Camera System', 'BP-U70', '메인 스튜디오', '조정실', 1, 'EA', '1003552', 'NORMAL', '', false),
  ('MS-003-F', '3', 'Battery Pack', 'Studio Camera System', 'BP-U70', '메인 스튜디오', '조정실', 1, 'EA', '1005533', 'NORMAL', '', false),
  ('MS-004-A', '4', 'Battery Charger', 'Studio Camera System', 'BC-U2A', '메인 스튜디오', '조정실', 1, 'EA', '21012000191', 'NORMAL', '', false),
  ('MS-004-B', '4', 'Battery Charger', 'Studio Camera System', 'BC-U2A', '메인 스튜디오', '조정실', 1, 'EA', '21012000192', 'NORMAL', '', false),
  ('MS-005-A', '5-1', 'Zoom Remote', 'Studio Camera System', 'ZC-LP', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-005-B', '5-1', 'Zoom Remote', 'Studio Camera System', 'ZC-LP', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-005-C', '5-1', 'Zoom Remote', 'Studio Camera System', 'ZC-LP', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-006', '5-2', 'Zoom Remote', 'Studio Camera System', 'ZC-LP', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-007-A', '6', 'SxS Memory Card 128GB', 'Studio Camera System', 'SBS-128G1C', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-007-B', '6', 'SxS Memory Card 128GB', 'Studio Camera System', 'SBS-128G1C', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-007-C', '6', 'SxS Memory Card 128GB', 'Studio Camera System', 'SBS-128G1C', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-007-D', '6', 'SxS Memory Card 128GB', 'Studio Camera System', 'SBS-128G1C', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-007-E', '6', 'SxS Memory Card 128GB', 'Studio Camera System', 'SBS-128G1C', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-007-F', '6', 'SxS Memory Card 128GB', 'Studio Camera System', 'SBS-128G1C', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-008-A', '7', 'External MIC', 'Studio Camera System', 'ECM-VG1', '메인 스튜디오', '조정실', 1, 'EA', '176994', 'NORMAL', '', false),
  ('MS-008-B', '7', 'External MIC', 'Studio Camera System', 'ECM-VG1', '메인 스튜디오', '조정실', 1, 'EA', '177427', 'NORMAL', '', false),
  ('MS-009-A', '8', 'Wireless MIC', 'Studio Camera System', 'UWP-D21', '메인 스튜디오', '조정실', 1, 'EA', 'Tx 706058 / Rx 705737', 'NORMAL', '', false),
  ('MS-009-B', '8', 'Wireless MIC', 'Studio Camera System', 'UWP-D21', '메인 스튜디오', '조정실', 1, 'EA', 'Tx 706057 / Rx 705736', 'NORMAL', '', false),
  ('MS-010-A', '9', 'Softcase', 'Studio Camera System', 'CC-193', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-010-B', '9', 'Softcase', 'Studio Camera System', 'CC-193', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-010-C', '9', 'Softcase', 'Studio Camera System', 'CC-193', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-011', '10', 'DSLR 카메라', 'Studio Camera System', 'Canon 5D Mark IV', '메인 스튜디오', '', 1, 'EA', '558038000373', 'NORMAL', '홍보팀', false),
  ('MS-012', '11', 'DSLR용 표준 줌 렌즈', 'Studio Camera System', 'EF 24-70mm F/2.8L II USM', '메인 스튜디오', '', 1, 'EA', '9697003275', 'NORMAL', '홍보팀', false),
  ('MS-013', '12', '대용량 리튬 이온 배터리', 'Studio Camera System', 'LP-E6NH', '메인 스튜디오', '', 1, 'EA', '4132C002', 'NORMAL', '홍보팀', false),
  ('MS-014', '13', '삼각대', 'Studio Camera System', 'HDV-3000', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-015-A', '14', 'Pan/Tilt Head', 'Camera Pan/Tilt Control System', 'MT-PT60', '메인 스튜디오', '스튜디오', 1, 'EA', '202012043', 'NORMAL', '', false),
  ('MS-015-B', '14', 'Pan/Tilt Head', 'Camera Pan/Tilt Control System', 'MT-PT60', '메인 스튜디오', '스튜디오', 1, 'EA', '202012059', 'NORMAL', '', false),
  ('MS-016-A', '15', 'Tripod Adapter', 'Camera Pan/Tilt Control System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-016-B', '15', 'Tripod Adapter', 'Camera Pan/Tilt Control System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-017', '16', 'Remote Controller', 'Camera Pan/Tilt Control System', 'MT-TX80s', '메인 스튜디오', '조정실', 1, 'EA', '202011024', 'NORMAL', '', false),
  ('MS-018', '17', '24'''' Prompter System', 'Prompter System', 'AJ-241BHWHD', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-019', '18', 'FreeSpeech Software', 'Prompter System', 'BF20801', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-020', '19', 'Operating Notebook PC', 'Prompter System', '', '메인 스튜디오', '조정실', 1, 'EA', '4TXA9FHR200263K', 'NORMAL', '', false),
  ('MS-021-A', '20', 'Tripod System for Pan/Tilt EFP Camera', 'Camera Support System', 'OZ-12CF2', '메인 스튜디오', '스튜디오', 1, 'SET', 'H122101003', 'NORMAL', '', false),
  ('MS-021-B', '20', 'Tripod System for Pan/Tilt EFP Camera', 'Camera Support System', 'OZ-12CF2', '메인 스튜디오', '스튜디오', 1, 'SET', 'H122008006', 'NORMAL', '', false),
  ('MS-022', '21', 'Head with 1 Pan Bar', 'Camera Support System', '100mm AGILE 12', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-023', '22', 'Tripod', 'Camera Support System', '100CF2', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-024', '23', 'Ground Spreader', 'Camera Support System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-025', '24', 'Soft Case', 'Camera Support System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-026', '25', 'Pan bar Plus Left', 'Camera Support System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-027-A', '26', 'Tripod System for Pan/Tilt EFP Camera', 'Camera Support System', 'OZ-18CF2', '메인 스튜디오', '스튜디오', 1, 'SET', 'H182101010', 'NORMAL', '', false),
  ('MS-027-B', '26', 'Tripod System for Pan/Tilt EFP Camera', 'Camera Support System', 'OZ-18CF2', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-028', '27', 'Head with 1 Pan Bar', 'Camera Support System', '100mm AGILE 18', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-029', '28', 'Tripod', 'Camera Support System', '100CF2', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-030', '29', 'Ground Spreader', 'Camera Support System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-031', '30', 'Soft Case', 'Camera Support System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-032', '31', 'Pan bar Plus Left', 'Camera Support System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-033-A', '32', 'Dolly', 'Camera Support System', 'DL-100', '메인 스튜디오', '스튜디오', 1, 'EA', 'D192011004', 'NORMAL', '', false),
  ('MS-033-B', '32', 'Dolly', 'Camera Support System', 'DL-100', '메인 스튜디오', '스튜디오', 1, 'EA', 'D192011005', 'NORMAL', '', false),
  ('MS-033-C', '32', 'Dolly', 'Camera Support System', 'DL-100', '메인 스튜디오', '스튜디오', 1, 'EA', 'D192011006', 'NORMAL', '', false),
  ('MS-034-A', '33', 'Wireless MIC System', 'Microphone System', 'EW100 G4', '메인 스튜디오', '조정실', 1, 'EA', '1480002899', 'NORMAL', '', false),
  ('MS-034-B', '33', 'Wireless MIC System', 'Microphone System', 'EW100 G4', '메인 스튜디오', '조정실', 1, 'EA', '1490002969', 'NORMAL', '', false),
  ('MS-034-C', '33', 'Wireless MIC System', 'Microphone System', 'EW100 G4', '메인 스튜디오', '조정실', 1, 'EA', '1490002980', 'NORMAL', '', false),
  ('MS-034-D', '33', 'Wireless MIC System', 'Microphone System', 'EW100 G4', '메인 스튜디오', '조정실', 1, 'EA', '1490002982', 'NORMAL', '', false),
  ('MS-035-A', '34', 'Wireless Camera', 'Microphone System', 'A2003-UHF', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-035-B', '34', 'Wireless Camera', 'Microphone System', 'A2003-UHF', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-036-A', '35', 'Antenna Booster', 'Microphone System', 'AB3-K', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-036-B', '35', 'Antenna Booster', 'Microphone System', 'AB3-K', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-037', '36', 'Wireless Antenna Splitter', 'Microphone System', 'ASA214', '메인 스튜디오', '서버실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-038-A', '37', 'Condenser Microphone for MultiPurpose', 'Microphone System', 'C414-XLII', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-038-B', '37', 'Condenser Microphone for MultiPurpose', 'Microphone System', 'C414-XLII', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-039-A', '38', 'MIC Stand', 'Microphone System', '23850-300-55', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-039-B', '38', 'MIC Stand', 'Microphone System', '23850-300-55', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-040', '39', '55'''' Studio Monitor', 'Monitoring System', '55'''' UHD', '메인 스튜디오', '스튜디오', 1, 'EA', '102INPT4K216', 'NORMAL', '', false),
  ('MS-041', '40', 'Monitor Cart', 'Monitoring System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-042', '41', 'SDI to HDMI Converter', 'Monitoring System', 'SDI to HDMI', '메인 스튜디오', '스튜디오', 1, 'EA', '7747691', 'NORMAL', '', false),
  ('MS-043-A', '42', 'Studio Monitor Speaker', 'Monitoring System', 'HS8', '메인 스튜디오', '스튜디오', 1, 'EA', 'KFBH01010', 'NORMAL', '', false),
  ('MS-043-B', '42', 'Studio Monitor Speaker', 'Monitoring System', 'HS8', '메인 스튜디오', '스튜디오', 1, 'EA', 'KFBH01011', 'NORMAL', '', false),
  ('MS-044-A', '43', 'Speaker Stand', 'Monitoring System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-044-B', '43', 'Speaker Stand', 'Monitoring System', 'Custom Made', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-045', '44', 'Headphone Amp', 'Monitoring System', 'HA8000-V2', '메인 스튜디오', '스튜디오', 1, 'EA', 'S201000507BRU', 'NORMAL', '', false),
  ('MS-046', '45', 'Stereo Headphone', 'Monitoring System', 'K271MK2', '메인 스튜디오', '조정실', 1, 'EA', 'UT0034-212907', 'BROKEN', 'UT0034-212907 파손', false),
  ('MS-047-A', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-B', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-C', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-D', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-E', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-F', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-G', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-H', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-I', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-J', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-K', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-L', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-M', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-N', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-O', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-P', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-Q', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-047-R', '46', '160W LED Panel Light', 'Studio Lighting System', 'COAVS-T200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false);

-- Batch 2
INSERT INTO equipments (id, original_index, name, category, spec, location, sub_location, quantity, unit, serial_number, status, notes, is_material)
VALUES
  ('MS-048-A', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-B', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-C', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-D', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-E', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-F', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-G', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-H', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-I', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-J', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-K', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-L', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-M', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-N', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-O', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-P', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-Q', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-048-R', '47', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-A', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-B', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-C', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-D', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-E', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-F', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-G', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-H', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-I', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-J', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-K', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-L', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-M', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-N', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-O', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-P', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-Q', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-049-R', '48', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-050-A', '49', '220W LED Spotlight', 'Studio Lighting System', 'COAVS-BL200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-050-B', '49', '220W LED Spotlight', 'Studio Lighting System', 'COAVS-BL200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-050-C', '49', '220W LED Spotlight', 'Studio Lighting System', 'COAVS-BL200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-050-D', '49', '220W LED Spotlight', 'Studio Lighting System', 'COAVS-BL200', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-051-A', '50', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-051-B', '50', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-051-C', '50', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-051-D', '50', '5600K, CRI 97 이상, DMX Dim', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-052-A', '51', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-052-B', '51', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-052-C', '51', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-052-D', '51', 'Barn Doors (4 Leaf)', 'Studio Lighting System', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-A', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-B', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-C', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-D', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-E', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-F', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-G', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-H', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-I', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-J', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-K', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-L', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-M', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-N', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-O', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-P', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-Q', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-R', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-S', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-T', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-U', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-053-V', '52', 'Light Hanger', 'Studio Lighting System', 'Cast Type', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-A', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-B', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-C', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-D', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-E', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-F', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-G', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-H', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-I', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-J', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-K', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-L', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-M', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-N', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-O', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-P', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-Q', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-R', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-S', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-T', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-U', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-054-V', '53', 'Safety Chain', 'Studio Lighting System', 'L=700', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-055-A', '54', 'Connector Box', 'Studio Lighting System', '3P15A 4OUT / XLR-3P', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-055-B', '54', 'Connector Box', 'Studio Lighting System', '3P15A 4OUT / XLR-3P', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-055-C', '54', 'Connector Box', 'Studio Lighting System', '3P15A 4OUT / XLR-3P', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-055-D', '54', 'Connector Box', 'Studio Lighting System', '3P15A 4OUT / XLR-3P', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-055-E', '54', 'Connector Box', 'Studio Lighting System', '3P15A 4OUT / XLR-3P', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-A', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-B', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-C', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false);

-- Batch 3
INSERT INTO equipments (id, original_index, name, category, spec, location, sub_location, quantity, unit, serial_number, status, notes, is_material)
VALUES
  ('MS-056-D', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-E', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-F', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-G', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-H', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-I', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-056-J', '55', 'Power EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:2 Type', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-A', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-B', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-C', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-D', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-E', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-F', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-G', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-H', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-I', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-057-J', '56', 'Signal EXT'''' Cord', 'Studio Lighting System', '2,000L / 1:1 Type / Belden-9841 & Neutrik Con''''', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-058-A', '57', 'Wall Pocket', 'Studio Lighting System', '4way (15A-15A-30A-30A)', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-058-B', '57', 'Wall Pocket', 'Studio Lighting System', '4way (15A-15A-30A-30A)', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-059', '58', 'Monitorized Image (3 Pattern) Screen', 'Studio Lighting System', '150'''' / REMOTE CONTROL', '메인 스튜디오', '스튜디오', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-060', '59', 'DMX Splitter', 'Studio Lighting System', '1 IN / 8 OUT', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-061', '60', 'Light DMX Control Console', 'Studio Lighting System', 'GOBO-200', '메인 스튜디오', '조정실', 1, 'EA', '2007G200600055', 'NORMAL', '', false),
  ('MS-062', '61', 'RD Unit Panel & Control Board', 'Studio Lighting System', 'DALI / 8RD / 4Scene Controller', '메인 스튜디오', '조정실', 1, 'SET', '', 'NORMAL', '', false),
  ('MS-063', '62', 'Pipe Grid', 'Studio Lighting System', '', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('MS-064', '63', '세트 디자인', '무대 세트 구성', '3D 이미지', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-065', '64', '메인 무대 세트 배경', '무대 세트 구성', '호리존 설치', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-066', '65', '메인 무대 세트', '무대 세트 구성', '무대 바닥 및 마감', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-067', '66', '서브 무대 세트 배경', '무대 세트 구성', '스탠딩 타입', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-068', '67', '무대 소품', '무대 세트 구성', '', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-069', '68', '소품 및 장비 보관', '무대 세트 구성', '제작', '메인 스튜디오', '스튜디오', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-070', '69', '냉방기', '무대 세트 구성', '', '메인 스튜디오', '서버실', 1, '식', '', 'NORMAL', '', false),
  ('MS-071', '70', 'HD 통합 솔루션', 'Production Video Switcher System', '410 PLUS', '메인 스튜디오', '조정실', 1, 'SET', 'VF-2050-0104', 'NORMAL', '', false),
  ('MS-072', '71', 'Control Panel', 'Production Video Switcher System', '', '메인 스튜디오', '조정실', 1, 'EA', 'NTIP36354755635', 'NORMAL', '', false),
  ('MS-073', '72', 'Virtual Set Editor 2', 'Production Video Switcher System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-074', '73', 'SDI/HDMI to NDI Converter', 'Production Video Switcher System', '', '메인 스튜디오', '조정실', 1, 'EA', '20072610669', 'NORMAL', '', false),
  ('MS-075', '74', 'SDI Distribute Amp (Mini Type)', 'Production Video Switcher System', '', '메인 스튜디오', '조정실', 1, 'EA', 'K0542550', 'NORMAL', '', false),
  ('MS-076', '75', 'Playout / Ingest / Scheduler Package System', 'Video Recording & Playout System', 'Marsis Server', '메인 스튜디오', '조정실', 1, 'SET', '16NZ5C3', 'NORMAL', '', false),
  ('MS-077', '76', 'Intel® Core™ i9', 'Video Recording & Playout System', 'i9-r10900X 3.7GHz,
4.7GHz Turbo, 10C, 19.25MB Cache, HT, (165W)', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-078', '77', 'non-ECC Memory', 'Video Recording & Playout System', '64GB DDR4 2666MHz ', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-079', '78', 'M.2 1TB PCIe NVMe Class 40 SSD', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-080', '79', '2.5'''' 1TB SATA Class 20 SSD', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-081-A', '80', 'GeForce RTX 2080', 'Video Recording & Playout System', 'INNO3D GeForce RTX 2080 Ti GAMING OC D6 11GB', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-081-B', '80', 'GeForce RTX 2080', 'Video Recording & Playout System', 'INNO3D GeForce RTX 2080 Ti GAMING OC D6 11GB', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-081-C', '80', 'GeForce RTX 2080', 'Video Recording & Playout System', 'INNO3D GeForce RTX 2080 Ti GAMING OC D6 11GB', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-082', '81', 'Windows 10 Pro 64bit', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-083-A', '82', 'Monitor 24''''', 'Video Recording & Playout System', 'P2419H', '메인 스튜디오', '조정실', 1, 'EA', 'CN-06HXTR-FCC00-11R-AAFU-A05', 'NORMAL', '', false),
  ('MS-083-B', '82', 'Monitor 24''''', 'Video Recording & Playout System', 'P2419H', '메인 스튜디오', '조정실', 1, 'EA', 'CN-06HXTR-FCC00-11R-AAGU-A05', 'NORMAL', '', false),
  ('MS-084', '83', 'I/O Board', 'Video Recording & Playout System', 'Duo2', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-085-A', '84', '1ch Marsys Playout License', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-085-B', '84', '1ch Marsys Playout License', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-086-A', '85', '1ch Marsys Ingest License', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-086-B', '85', '1ch Marsys Ingest License', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-087', '86', 'Marsys Scheduler License', 'Video Recording & Playout System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-088', '87', 'NAS Storage System', 'Video Recording & Playout System', 'ReadyRECOVER 4312', '메인 스튜디오', '서버실', 1, 'SET', '603199E70007F', 'NORMAL', '', false),
  ('MS-089', '88', 'EDIUS NLE Network System', 'NLE System', 'ENS-5500', '메인 스튜디오', '조정실', 1, 'SET', '4CE1023RF2', 'NORMAL', '', false),
  ('MS-090', '89', 'CPU / RAM / SSD / SATA / VGA', 'NLE System', '3.2GHz 8C CPU
32GB RAM
M2 512GB SSD
6TB SATA
5G VGA', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-091', '90', 'HD/SD SDI 입/출력, HDMI 출력, Audio Monitoring Out', 'NLE System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-092', '91', 'EDIUS Pro 9 License', 'NLE System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-093', '92', '24인치 Dual Display', 'NLE System', '', '메인 스튜디오', '조정실', 1, 'EA', '6CM03819K2', 'NORMAL', '', false),
  ('MS-094', '93', 'USB 키보드 및 마우스', 'NLE System', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-095', '94', '18.5'''' FHD Monitor (QC & PGM)', 'Video QC & Monitoring System', 'LVM-182W', '메인 스튜디오', '조정실', 1, 'EA', 'LV182AU0007', 'NORMAL', '', false),
  ('MS-096', '95', '55'''' LED Monitor for Operating', 'Video QC & Monitoring System', '55'''' UHD', '메인 스튜디오', '조정실', 1, 'EA', '102INZY4K221', 'NORMAL', '', false),
  ('MS-097', '96', 'Wall Mount Bracket', 'Video QC & Monitoring System', 'Custom Made', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-098', '97', 'Sync Generator', 'Sync & Clock System', 'Mini Sync Generator', '메인 스튜디오', '서버실', 1, 'EA', '7612741', 'NORMAL', '', false),
  ('MS-099', '98', 'Mater Clock Generator', 'Sync & Clock System', 'BT-114M', '메인 스튜디오', '서버실', 1, 'EA', '2021.02.047', 'NORMAL', '', false),
  ('MS-100', '99-1', 'Clock Display', 'Sync & Clock System', 'BT-1143', '메인 스튜디오', '스튜디오', 1, 'EA', '2021.02.048', 'NORMAL', '', false),
  ('MS-101', '99-2', 'Clock Display', 'Sync & Clock System', 'BT-1143', '메인 스튜디오', '서버실', 1, 'EA', '2021.02.049', 'NORMAL', '', false),
  ('MS-102', '100', 'Digital Audio Mixing Console', 'Audio Mixer System', 'QL1', '메인 스튜디오', '조정실', 1, 'SET', 'KAAP01002', 'NORMAL', '', false),
  ('MS-103', '101', '8ch Analog I/O Board', 'Audio Mixer System', 'MY8-ADDA96', '메인 스튜디오', '조정실', 1, 'EA', 'YAAK01019', 'NORMAL', '', false),
  ('MS-104', '102', '16ch AES/EBU I/O Board', 'Audio Mixer System', 'MY16-AE', '메인 스튜디오', '조정실', 1, 'EA', 'YAAJ01001', 'NORMAL', '', false),
  ('MS-105-A', '103', 'Control Room Monitor Speaker', 'Audio QC & Monitoring System', 'HS8', '메인 스튜디오', '조정실', 1, 'EA', 'KFBH01012', 'NORMAL', '', false),
  ('MS-105-B', '103', 'Control Room Monitor Speaker', 'Audio QC & Monitoring System', 'HS8', '메인 스튜디오', '조정실', 1, 'EA', 'KFBH01016', 'NORMAL', '', false),
  ('MS-106-A', '104', 'Speaker Stand', 'Audio QC & Monitoring System', 'Custom Made', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-106-B', '104', 'Speaker Stand', 'Audio QC & Monitoring System', 'Custom Made', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-107', '105', 'Audio Tally Control Unit', 'Audio QC & Monitoring System', 'BTA-120', '메인 스튜디오', '서버실', 1, 'EA', '2021.02.050', 'NORMAL', '', false),
  ('MS-108-A', '106-1', 'ON-AIR Lamp', 'Audio QC & Monitoring System', 'BT-1140D', '메인 스튜디오', '스튜디오', 1, 'EA', '2021.02.037', 'NORMAL', '', false),
  ('MS-108-B', '106-1', 'ON-AIR Lamp', 'Audio QC & Monitoring System', 'BT-1140D', '메인 스튜디오', '스튜디오', 1, 'EA', '2021.02.038', 'NORMAL', '', false),
  ('MS-109-A', '106-1', 'ON-AIR Lamp', 'Audio QC & Monitoring System', 'BT-1140D', '메인 스튜디오', '조정실', 1, 'EA', '2021.02.042', 'NORMAL', '', false),
  ('MS-109-B', '106-1', 'ON-AIR Lamp', 'Audio QC & Monitoring System', 'BT-1140D', '메인 스튜디오', '조정실', 1, 'EA', '2021.02.043', 'NORMAL', '', false),
  ('MS-110', '107', 'Base Station', 'Wireless Intercom System', 'BS1000', '메인 스튜디오', '조정실', 1, 'EA', 'BS10021FFY001', 'NORMAL', '', false),
  ('MS-111', '108', 'Gooseneck MIC', 'Wireless Intercom System', 'GM26', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-112', '109', 'Antenna with Antenna Cable', 'Wireless Intercom System', 'ANT-70', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-113-A', '110', 'Wireless Belt Pack', 'Wireless Intercom System', 'LTWI-BP850', '메인 스튜디오', '조정실', 1, 'EA', 'BAWBP2037Y012', 'NORMAL', '', false),
  ('MS-113-B', '110', 'Wireless Belt Pack', 'Wireless Intercom System', 'LTWI-BP850', '메인 스튜디오', '조정실', 1, 'EA', 'BAWBP2037Y013', 'NORMAL', '', false),
  ('MS-113-C', '110', 'Wireless Belt Pack', 'Wireless Intercom System', 'LTWI-BP850', '메인 스튜디오', '조정실', 1, 'EA', 'BAWBP2037Y014', 'NORMAL', '', false),
  ('MS-113-D', '110', 'Wireless Belt Pack', 'Wireless Intercom System', 'LTWI-BP850', '메인 스튜디오', '조정실', 1, 'EA', 'BAWBP2037Y015', 'NORMAL', '', false),
  ('MS-114-A', '111', 'Belt Pack Pouch', 'Wireless Intercom System', 'BPPCH100', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-114-B', '111', 'Belt Pack Pouch', 'Wireless Intercom System', 'BPPCH100', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-114-C', '111', 'Belt Pack Pouch', 'Wireless Intercom System', 'BPPCH100', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-114-D', '111', 'Belt Pack Pouch', 'Wireless Intercom System', 'BPPCH100', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-115-A', '112', 'Belt Pack Battery', 'Wireless Intercom System', 'LTWI-BAT50R', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-115-B', '112', 'Belt Pack Battery', 'Wireless Intercom System', 'LTWI-BAT50R', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-115-C', '112', 'Belt Pack Battery', 'Wireless Intercom System', 'LTWI-BAT50R', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-115-D', '112', 'Belt Pack Battery', 'Wireless Intercom System', 'LTWI-BAT50R', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-116', '113', 'Battery Charger (7포트)', 'Wireless Intercom System', 'LTWI-BATCHG125', '메인 스튜디오', '조정실', 1, 'EA', 'BTCHG21JAY005', 'NORMAL', '', false),
  ('MS-117-A', '114', 'Headset for Camera & AE', 'Wireless Intercom System', 'LMH-10', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-117-B', '114', 'Headset for Camera & AE', 'Wireless Intercom System', 'LMH-10', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-118-A', '115', 'Earset (Tube Type) for 출연자', 'Wireless Intercom System', 'PTE-850', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-118-B', '115', 'Earset (Tube Type) for 출연자', 'Wireless Intercom System', 'PTE-850', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-142', '138-1', 'Monitoring Chair', '조정실 환경 구성', '제작', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false);

-- Batch 4
INSERT INTO equipments (id, original_index, name, category, spec, location, sub_location, quantity, unit, serial_number, status, notes, is_material)
VALUES
  ('MS-143-A', '138-2', 'Monitoring Chair', '조정실 환경 구성', '제작', '메인 스튜디오', '서버실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-143-B', '138-2', 'Monitoring Chair', '조정실 환경 구성', '제작', '메인 스튜디오', '서버실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-144-A', '139', 'Equipment Cabinet', '조정실 환경 구성', '제작', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-144-B', '139', 'Equipment Cabinet', '조정실 환경 구성', '제작', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('MS-145', '140', 'Studio Blind', '조정실 환경 구성', '제작', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('MS-146', '141', '흡음보드 설치', '조정실 환경 구성', '제작', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('MS-147', '142', '기계실 샷시 공사', '조정실 환경 구성', '', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('MS-148', '143', '레일 등 설치 및 마감 인테리어', '조정실 환경 구성', '', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('MS-149', '144', '실외기실 분리 공사', '조정실 환경 구성', '', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('MS-150', '145', '분전반 설치', '조정실 환경 구성', '', '메인 스튜디오', '조정실', 1, '식', '', 'NORMAL', '', false),
  ('1A-001-A', '146', 'NXCAM Full HD Camcorder', 'Camera System', 'PXW-Z90V', '스튜디오 A', '스튜디오 A', 1, 'EA', '1006396', 'NORMAL', '', false),
  ('1A-001-B', '146', 'NXCAM Full HD Camcorder', 'Camera System', 'PXW-Z90V', '스튜디오 A', '스튜디오 A', 1, 'EA', '1006349', 'NORMAL', '', false),
  ('1B-001-A', '146', 'NXCAM Full HD Camcorder', 'Camera System', 'PXW-Z90V', '스튜디오 B', '스튜디오 B', 1, 'EA', '1006324', 'NORMAL', '', false),
  ('1B-001-B', '146', 'NXCAM Full HD Camcorder', 'Camera System', 'PXW-Z90V', '스튜디오 B', '스튜디오 B', 1, 'EA', '1006426', 'NORMAL', '', false),
  ('1A-002-A', '147', 'Condenser Microphone', 'Camera System', 'ECM-VG1', '스튜디오 A', '조정실', 1, 'EA', '177426', 'NORMAL', '', false),
  ('1A-002-B', '147', 'Condenser Microphone', 'Camera System', 'ECM-VG1', '스튜디오 A', '조정실', 1, 'EA', '175636', 'NORMAL', '', false),
  ('1A-003-A', '148', 'Wireless Microphone', 'Camera System', 'UWP-D21', '스튜디오 A', '조정실', 1, 'EA', 'Tx 706073 / Rx 705752', 'NORMAL', '', false),
  ('1A-003-B', '148', 'Wireless Microphone', 'Camera System', 'UWP-D21', '스튜디오 A', '조정실', 1, 'EA', 'Tx 706074 / Rx 705753', 'NORMAL', '', false),
  ('1A-004-A', '149', 'Memory Card', 'Camera System', '512GB', '스튜디오 A', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-004-B', '149', 'Memory Card', 'Camera System', '512GB', '스튜디오 A', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-004-C', '149', 'Memory Card', 'Camera System', '512GB', '스튜디오 A', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-004-D', '149', 'Memory Card', 'Camera System', '512GB', '스튜디오 A', '조정실', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-005-A', '150', 'Charger & Battery Pack', 'Camera System', 'AC-VQV10', '스튜디오 A', '조정실', 1, 'EA', '1000411', 'NORMAL', '', false),
  ('1A-005-B', '150', 'Charger & Battery Pack', 'Camera System', 'AC-VQV10', '스튜디오 A', '조정실', 1, 'EA', '1000372', 'NORMAL', '', false),
  ('1A-005-C', '150', 'Charger & Battery Pack', 'Camera System', 'AC-VQV10', '스튜디오 A', '조정실', 1, 'EA', '1000413', 'NORMAL', '', false),
  ('1A-005-D', '150', 'Charger & Battery Pack', 'Camera System', 'AC-VQV10', '스튜디오 A', '조정실', 1, 'EA', '1000414', 'NORMAL', '', false),
  ('1A-006-A', '151', 'Tripod System', 'Camera System', 'I-605RM', '스튜디오 A', '스튜디오 A', 1, 'SET', '', 'NORMAL', '', false),
  ('1A-006-B', '151', 'Tripod System', 'Camera System', 'I-605RM', '스튜디오 A', '스튜디오 A', 1, 'SET', '', 'NORMAL', '', false),
  ('1B-002-A', '151', 'Tripod System', 'Camera System', 'I-605RM', '스튜디오 B', '스튜디오 B', 1, 'SET', '', 'NORMAL', '', false),
  ('1B-002-B', '151', 'Tripod System', 'Camera System', 'I-605RM', '스튜디오 B', '스튜디오 B', 1, 'SET', '', 'NORMAL', '', false),
  ('1A-007-A', '152', 'Wireless MIC System', 'Microphone System', 'EW100G4', '스튜디오 A', '스튜디오 A', 1, 'EA', '1490002951', 'NORMAL', '', false),
  ('1A-007-B', '152', 'Wireless MIC System', 'Microphone System', 'EW100G4', '스튜디오 A', '스튜디오 A', 1, 'EA', '1490002952', 'NORMAL', '', false),
  ('1A-007-C', '152', 'Wireless MIC System', 'Microphone System', 'EW100G4', '스튜디오 A', '스튜디오 A', 1, 'EA', '1490002953', 'NORMAL', '', false),
  ('1B-003-A', '152', 'Wireless MIC System', 'Microphone System', 'EW100G4', '스튜디오 B', '스튜디오 B', 1, 'EA', '1490002966', 'NORMAL', '', false),
  ('1B-003-B', '152', 'Wireless MIC System', 'Microphone System', 'EW100G4', '스튜디오 B', '스튜디오 B', 1, 'EA', '1480002900', 'NORMAL', '', false),
  ('1B-003-C', '152', 'Wireless MIC System', 'Microphone System', 'EW100G4', '스튜디오 B', '스튜디오 B', 1, 'EA', '1480002901', 'NORMAL', '', false),
  ('1A-008', '153', 'Condenser MIC Set', 'Microphone System', 'AT2020', '스튜디오 A', '스튜디오 A', 1, 'SET', '', 'NORMAL', '', false),
  ('1B-004', '153', 'Condenser MIC Set', 'Microphone System', 'AT2020', '스튜디오 B', '스튜디오 B', 1, 'SET', '', 'NORMAL', '', false),
  ('1A-009', '154', 'MIC Stand', 'Microphone System', '', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-005', '154', 'MIC Stand', 'Microphone System', '', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-010', '155', 'Pop Filter', 'Microphone System', '', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-006', '155', 'Pop Filter', 'Microphone System', '', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-011', '156', 'Audio Interface (Focusrite. Scarlett Solo)', 'Microphone System', '', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-007', '156', 'Audio Interface (Focusrite. Scarlett Solo)', 'Microphone System', '', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-012-A', '157', 'TV Monitor 43''''', 'Monitoring System', '43'''' UHD', '스튜디오 A', '스튜디오 A', 1, 'EA', '102INGQ8J543', 'NORMAL', '', false),
  ('1A-012-B', '157', 'TV Monitor 43''''', 'Monitoring System', '43'''' UHD', '스튜디오 A', '스튜디오 A', 1, 'EA', '102INSE8J542', 'NORMAL', '', false),
  ('1B-008-A', '157', 'TV Monitor 43''''', 'Monitoring System', '43'''' UHD', '스튜디오 B', '스튜디오 B', 1, 'EA', '102INMF8J547', 'NORMAL', '', false),
  ('1B-008-B', '157', 'TV Monitor 43''''', 'Monitoring System', '43'''' UHD', '스튜디오 B', '스튜디오 B', 1, 'EA', '102INDP8J546', 'NORMAL', '', false),
  ('1A-013-A', '158', 'TV Stand', 'Monitoring System', 'Custom Made', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-013-B', '158', 'TV Stand', 'Monitoring System', 'Custom Made', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-009-A', '158', 'TV Stand', 'Monitoring System', 'Custom Made', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-009-B', '158', 'TV Stand', 'Monitoring System', 'Custom Made', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-014-A', '159', 'Monitoring Speaker', 'Monitoring System', 'HS5', '스튜디오 A', '스튜디오 A', 1, 'EA', 'KFAZ01146', 'NORMAL', '', false),
  ('1A-014-B', '159', 'Monitoring Speaker', 'Monitoring System', 'HS5', '스튜디오 A', '스튜디오 A', 1, 'EA', 'KFAZ01153', 'NORMAL', '', false),
  ('1B-010-A', '159', 'Monitoring Speaker', 'Monitoring System', 'HS5', '스튜디오 B', '스튜디오 B', 1, 'EA', 'KFAZ01207', 'NORMAL', '', false),
  ('1B-010-B', '159', 'Monitoring Speaker', 'Monitoring System', 'HS5', '스튜디오 B', '스튜디오 B', 1, 'EA', 'KFAZ01209', 'NORMAL', '', false),
  ('1A-015-A', '160', 'Speaker Stand', 'Monitoring System', 'Custom Made', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-015-B', '160', 'Speaker Stand', 'Monitoring System', 'Custom Made', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-011-A', '160', 'Speaker Stand', 'Monitoring System', 'Custom Made', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-011-B', '160', 'Speaker Stand', 'Monitoring System', 'Custom Made', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-016', '161', '배경 및 무대 세트용 전동 스크린', 'Lighting System', '120''''', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-012', '161', '배경 및 무대 세트용 전동 스크린', 'Lighting System', '120''''', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-A', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-B', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-C', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-D', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-E', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-F', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-G', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-017-H', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-A', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-B', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-C', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-D', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-E', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-F', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-G', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-013-H', '162', 'LED Rail Light', 'Lighting System', 'Lali Type 20W / 주문제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-018', '163', '4000K, CRI 90 이상, Dali 제어', 'Lighting System', '', '스튜디오 A', '스튜디오 A', 1, '', '', 'NORMAL', '', false),
  ('1A-019-A', '164', '4접점 Lail System', 'Lighting System', '3M', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-019-B', '164', '4접점 Lail System', 'Lighting System', '3M', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-019-C', '164', '4접점 Lail System', 'Lighting System', '3M', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-014-A', '164', '4접점 Lail System', 'Lighting System', '3M', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-014-B', '164', '4접점 Lail System', 'Lighting System', '3M', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-014-C', '164', '4접점 Lail System', 'Lighting System', '3M', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-A', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-B', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-C', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-D', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-E', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-F', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-G', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-H', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-I', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-020-J', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-A', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-B', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-C', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-D', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-E', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false);

-- Batch 5
INSERT INTO equipments (id, original_index, name, category, spec, location, sub_location, quantity, unit, serial_number, status, notes, is_material)
VALUES
  ('1B-015-F', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-G', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-H', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-I', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-015-J', '165', '4접점 Lail Socket', 'Lighting System', '4접점 / Power & Dali Signal', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-021', '166', '4Sceine Control S/W', 'Lighting System', 'Helvar', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-016', '166', '4Sceine Control S/W', 'Lighting System', 'Helvar', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-022', '167', 'Digidim Dimer Module', 'Lighting System', 'DIGIDIM 474', '스튜디오 A', '스튜디오 A', 1, '식', '', 'NORMAL', '', false),
  ('1A-023', '168', 'AV Switcher with Streaming', 'AV Mixing & Streaming System', 'MCX-500', '스튜디오 A', '스튜디오 A', 1, 'EA', '19134.19138', 'NORMAL', '', false),
  ('1B-017', '168', 'AV Switcher with Streaming', 'AV Mixing & Streaming System', 'MCX-500', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-024', '169', 'Audio Mixer', 'AV Mixing & Streaming System', 'MG10XU', '스튜디오 A', '스튜디오 A', 1, 'EA', 'KGAZ01008', 'NORMAL', '', false),
  ('1B-018', '169', 'Audio Mixer', 'AV Mixing & Streaming System', 'MG10XU', '스튜디오 B', '스튜디오 B', 1, 'EA', 'KGAZ01009', 'NORMAL', '', false),
  ('1A-025', '170', 'Workstation', 'Video Editing System', 'iMac 27형', '스튜디오 A', '스튜디오 A', 1, 'EA', 'C02F62CLPN7C', 'NORMAL', '', false),
  ('1B-019', '170', 'Workstation', 'Video Editing System', 'iMac 27형', '스튜디오 B', '스튜디오 B', 1, 'EA', 'C02F62UBPN7C', 'NORMAL', '', false),
  ('1A-026', '171', 'I/O Board Thunderbolt3 Cable', 'Video Editing System', 'Ultra Studio HD Mini', '스튜디오 A', '스튜디오 A', 1, 'EA', '7893260', 'NORMAL', '', false),
  ('1B-020', '171', 'I/O Board Thunderbolt3 Cable', 'Video Editing System', 'Ultra Studio HD Mini', '스튜디오 B', '스튜디오 B', 1, 'EA', '7893269', 'NORMAL', '', false),
  ('1A-027', '172', 'Thunderbolt3 Cable (2M)', 'Video Editing System', '', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-021', '172', 'Thunderbolt3 Cable (2M)', 'Video Editing System', '', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-028', '173', 'Editing Software', 'Video Editing System', 'FCP X Motion
5 Compressor 4', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', false),
  ('1B-022', '173', 'Editing Software', 'Video Editing System', 'FCP X Motion
5 Compressor 4', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', false),
  ('1A-039', '184', '세트 디자인', '무대 세트 및 구성', '3D 이미지', '스튜디오 A', '스튜디오 A', 1, '식', '', 'NORMAL', '', false),
  ('1B-033', '184', '세트 디자인', '무대 세트 및 구성', '3D 이미지', '스튜디오 B', '스튜디오 B', 1, '식', '', 'NORMAL', '', false),
  ('1A-040', '185', '1인 방송 무대 세트', '무대 세트 및 구성', '', '스튜디오 A', '스튜디오 A', 1, '식', '', 'NORMAL', '', false),
  ('1B-034', '185', '1인 방송 무대 세트', '무대 세트 및 구성', '', '스튜디오 B', '스튜디오 B', 1, '식', '', 'NORMAL', '', false),
  ('1A-041', '186', '무대 소품', '무대 세트 및 구성', '', '스튜디오 A', '스튜디오 A', 1, '식', '', 'NORMAL', '', false),
  ('1B-035', '186', '무대 소품', '무대 세트 및 구성', '', '스튜디오 B', '스튜디오 B', 1, '식', '', 'NORMAL', '', false),
  ('MS-119', '116', 'Studio 촬영 세트', 'System Installation', '', '메인 스튜디오', '조정실', 1, 'EA', '', 'NORMAL', '', true),
  ('MS-120', '117', 'Operating Console Desk', 'System Installation', 'Custom Made', '메인 스튜디오', '조정실', 6, 'BAY', '', 'NORMAL', '', true),
  ('MS-121', '118', 'Operating Chair', 'System Installation', '', '메인 스튜디오', '조정실', 3, 'EA', '', 'NORMAL', '', true),
  ('MS-122', '119', '19'''' Rack Cabinet', 'System Installation', '41RU x 1000D mm', '메인 스튜디오', '서버실', 5, 'EA', '', 'NORMAL', '', true),
  ('MS-123', '120-1', 'Power Distribute Unit', 'System Installation', '220V', '메인 스튜디오', '조정실', 1, 'EA', '2021.02.051', 'NORMAL', '', true),
  ('MS-124', '120-2', 'Power Distribute Unit', 'System Installation', '220V', '메인 스튜디오', '서버실', 5, 'EA', '2021.02.052, 2021.02.053, 2021.02.054, 2021.02.055, 2021.02.056', 'NORMAL', '', true),
  ('MS-125', '121', 'Signal Wall Box', 'System Installation', 'Custom Made', '메인 스튜디오', '스튜디오', 2, 'EA', '', 'NORMAL', '', true),
  ('MS-126', '122', '5C HDTV Video Cable', 'System Installation', 'L-4.5CHD', '메인 스튜디오', '스튜디오', 3000, 'M', '', 'NORMAL', '', true),
  ('MS-127', '123', 'Analog Audio Cable', 'System Installation', 'L-2B2AL', '메인 스튜디오', '스튜디오', 1000, 'M', '', 'NORMAL', '', true),
  ('MS-128', '124', 'Digital Audio Cable', 'System Installation', 'DA-202AT', '메인 스튜디오', '스튜디오', 600, 'M', '', 'NORMAL', '', true),
  ('MS-129', '125', 'MIC Cable', 'System Installation', 'L-2T2S', '메인 스튜디오', '스튜디오', 600, 'M', '', 'NORMAL', '', true),
  ('MS-130', '126', 'UTP Cable', 'System Installation', 'CAT.6', '메인 스튜디오', '스튜디오', 600, 'M', '', 'NORMAL', '', true),
  ('MS-131', '127', 'Control Cable', 'System Installation', '10C', '메인 스튜디오', '스튜디오', 100, 'M', '', 'NORMAL', '', true),
  ('MS-132', '128', 'Power Cable', 'System Installation', 'TFR-CV 2.5SQ 3C', '메인 스튜디오', '스튜디오', 200, 'M', '', 'NORMAL', '', true),
  ('MS-133', '129', 'Power Cable', 'System Installation', 'TFR-CV 4.0SQ 3C', '메인 스튜디오', '스튜디오', 100, 'M', '', 'NORMAL', '', true),
  ('MS-134', '130', 'Ground Cable', 'System Installation', 'GV 10SQ 1C', '메인 스튜디오', '스튜디오', 50, 'M', '', 'NORMAL', '', true),
  ('MS-135', '131', '5C BNC Connector', 'System Installation', 'BCP-B53', '메인 스튜디오', '스튜디오', 300, 'M', '', 'NORMAL', '', true),
  ('MS-136', '132', 'XLR Connector', 'System Installation', 'NC3FXX/MXX', '메인 스튜디오', '스튜디오', 50, '조', '', 'NORMAL', '', true),
  ('MS-137', '133', 'RJ-45 Connector', 'System Installation', 'CAT.6', '메인 스튜디오', '스튜디오', 100, 'EA', '', 'NORMAL', '', true),
  ('MS-138', '134', 'Cable Label', 'System Installation', 'TAG 9L-105', '메인 스튜디오', '스튜디오', 100, '매', '', 'NORMAL', '', true),
  ('MS-139', '135', 'Video Patch Panel', 'System Installation', '', '메인 스튜디오', '서버실', 1, 'EA', '', 'NORMAL', '', true),
  ('MS-140', '136', 'Audio Patch Panel', 'System Installation', '', '메인 스튜디오', '서버실', 1, 'EA', '', 'NORMAL', '', true),
  ('MS-141', '137', 'LCD KVM S/W', 'System Installation', '', '메인 스튜디오', '서버실', 1, 'EA', 'Z8KA-082-0014', 'NORMAL', '', true),
  ('1A-029', '174', 'Half Rack', 'System Installation', '제작', '스튜디오 A', '스튜디오 A', 1, 'EA', '', 'NORMAL', '', true),
  ('1B-023', '174', 'Half Rack', 'System Installation', '제작', '스튜디오 B', '스튜디오 B', 1, 'EA', '', 'NORMAL', '', true),
  ('1A-030', '175', '5C HDTV Video Cable', 'System Installation', 'L-4.5CHD', '스튜디오 A', '스튜디오 A', 300, 'M', '', 'NORMAL', '', true),
  ('1B-024', '175', '5C HDTV Video Cable', 'System Installation', 'L-4.5CHD', '스튜디오 B', '스튜디오 B', 300, 'M', '', 'NORMAL', '', true),
  ('1A-031', '176', 'Analog Audio Cable', 'System Installation', 'L-2B2AL', '스튜디오 A', '스튜디오 A', 200, 'M', '', 'NORMAL', '', true),
  ('1B-025', '176', 'Analog Audio Cable', 'System Installation', 'L-2B2AL', '스튜디오 B', '스튜디오 B', 200, 'M', '', 'NORMAL', '', true),
  ('1A-032', '177', 'MIC Cable', 'System Installation', 'L-2T2S', '스튜디오 A', '스튜디오 A', 100, 'M', '', 'NORMAL', '', true),
  ('1B-026', '177', 'MIC Cable', 'System Installation', 'L-2T2S', '스튜디오 B', '스튜디오 B', 100, 'M', '', 'NORMAL', '', true),
  ('1A-033', '178', 'UTP Cable', 'System Installation', 'CAT.6', '스튜디오 A', '스튜디오 A', 100, 'M', '', 'NORMAL', '', true),
  ('1B-027', '178', 'UTP Cable', 'System Installation', 'CAT.6', '스튜디오 B', '스튜디오 B', 100, 'M', '', 'NORMAL', '', true),
  ('1A-034', '179', 'Power Cable', 'System Installation', 'TFR-CV 2.5SQ 3C', '스튜디오 A', '스튜디오 A', 100, 'M', '', 'NORMAL', '', true),
  ('1B-028', '179', 'Power Cable', 'System Installation', 'TFR-CV 2.5SQ 3C', '스튜디오 B', '스튜디오 B', 100, 'M', '', 'NORMAL', '', true),
  ('1A-035', '180', '5C BNC Connector', 'System Installation', 'BCP-B53', '스튜디오 A', '스튜디오 A', 50, 'EA', '', 'NORMAL', '', true),
  ('1B-029', '180', '5C BNC Connector', 'System Installation', 'BCP-B53', '스튜디오 B', '스튜디오 B', 50, 'EA', '', 'NORMAL', '', true),
  ('1A-036', '181', 'XLR Connector', 'System Installation', 'NC3FXX/MXX', '스튜디오 A', '스튜디오 A', 20, '조', '', 'NORMAL', '', true),
  ('1B-030', '181', 'XLR Connector', 'System Installation', 'NC3FXX/MXX', '스튜디오 B', '스튜디오 B', 20, '조', '', 'NORMAL', '', true),
  ('1A-037', '182', 'RJ-45 Connector', 'System Installation', 'CAT.6', '스튜디오 A', '스튜디오 A', 50, 'EA', '', 'NORMAL', '', true),
  ('1B-031', '182', 'RJ-45 Connector', 'System Installation', 'CAT.6', '스튜디오 B', '스튜디오 B', 50, 'EA', '', 'NORMAL', '', true),
  ('1A-038', '183', 'Cable Label', 'System Installation', 'TAG 9L-105', '스튜디오 A', '스튜디오 A', 20, '매', '', 'NORMAL', '', true),
  ('1B-032', '183', 'Cable Label', 'System Installation', 'TAG 9L-105', '스튜디오 B', '스튜디오 B', 20, '매', '', 'NORMAL', '', true);

